# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
lacteos = Category.create(name: 'Lacteos')
Category.create(name: 'Menestras')
azucar = Category.create(name: 'Azucar')
arroz = Category.create(name: 'Arroz')
leche_gloria = Product.create(name:"Leche Gloria en latas", sku: 'kldo212', unit_of_measurement:'latas', description: 'leche en latas de 500ml', trademark: 'Gloria', category: lacteos)
azucar_cartavio = Product.create(name:"Azucar Cartavio a granel", sku: 'dffs0', unit_of_measurement:'Kg', description: 'Azucar a granel en sacos de 20Kg', trademark: 'Cartavio', category: azucar)
arroz_paisana = Product.create(name:"Arroz paisana a granel", sku: 'dadasd', unit_of_measurement:'Kg', description: 'Arroz a granel en sacos de 20Kg', trademark: 'Paisana', category: arroz)
ProductLot.create(quantity: 500, sanitary_registry: 'AAAABBBBB', due_date: Date.strptime('31/12/2016', '%d/%m/%Y'), lot_number: '12345678', production_date: Date.strptime('01/01/2016', '%d/%m/%Y'), product: leche_gloria)
ProductLot.create(quantity: 125, sanitary_registry: 'AAAABBBBB', due_date: Date.strptime('24/2/2017', '%d/%m/%Y'), lot_number: '12345678', production_date: Date.strptime('01/01/2016', '%d/%m/%Y'), product: leche_gloria)
ProductLot.create(quantity: 1200, sanitary_registry: 'AAAABBBBB', due_date: Date.strptime('3/3/2017', '%d/%m/%Y'), lot_number: '12345678', production_date: Date.strptime('01/01/2016', '%d/%m/%Y'), product: leche_gloria)
ProductLot.create(quantity: 42, sanitary_registry: 'AAAABBBBB', due_date: Date.strptime('16/4/2017', '%d/%m/%Y'), lot_number: '12345678', production_date: Date.strptime('01/01/2016', '%d/%m/%Y'), product: leche_gloria)
ProductLot.create(quantity: 0, sanitary_registry: 'AAAABBBBB', due_date: Date.strptime('26/3/2017', '%d/%m/%Y'), lot_number: '12345678', production_date: Date.strptime('01/01/2016', '%d/%m/%Y'), product: azucar_cartavio)
ProductLot.create(quantity: 500, sanitary_registry: 'AAAABBBBB', due_date: Date.strptime('5/2/2017', '%d/%m/%Y'), lot_number: '12345678', production_date: Date.strptime('01/01/2016', '%d/%m/%Y'), product: azucar_cartavio)
ProductLot.create(quantity: 500, sanitary_registry: 'AAAABBBBB', due_date: Date.strptime('19/7/2017', '%d/%m/%Y'), lot_number: '12345678', production_date: Date.strptime('01/01/2016', '%d/%m/%Y'), product: azucar_cartavio)
ProductLot.create(quantity: 500, sanitary_registry: 'AAAABBBBB', due_date: Date.strptime('16/9/2017', '%d/%m/%Y'), lot_number: '12345678', production_date: Date.strptime('01/01/2016', '%d/%m/%Y'), product: arroz_paisana)
ProductLot.create(quantity: 500, sanitary_registry: 'AAAABBBBB', due_date: Date.strptime('16/8/2017', '%d/%m/%Y'), lot_number: '12345678', production_date: Date.strptime('01/01/2016', '%d/%m/%Y'), product: arroz_paisana)
ProductLot.create(quantity: 500, sanitary_registry: 'AAAABBBBB', due_date: Date.strptime('27/8/2017', '%d/%m/%Y'), lot_number: '12345678', production_date: Date.strptime('01/01/2016', '%d/%m/%Y'), product: arroz_paisana)
pepe = Supplier.create(name: 'Comercial Pepe', ruc: '12345678901', address: 'Av. La marina 123', telephone: '1234567', contact: 'Pepe el Toro', active: 1)
lucho = Supplier.create(name: 'Comercial Lucho', ruc: '12345678901', address: 'Av. La marina 123', telephone: '1234567', contact: 'Luchin', active: 1)
pepelucho = Supplier.create(name: 'Comercial PepeLucho', ruc: '12345678901', address: 'Av. La marina 123', telephone: '1234567', contact: 'PepeLucho', active: 1)
oruga = Client.create(name: 'Oruga Tech', ruc: '12345678901', billing_address: 'Av. Javier Prado 123', delivery_address: 'Av. Universitaria 987', telephone: '1234567', contact: 'Bambucha', active: 1)
hospital = Client.create(name: 'Hospital Santa Rosa', ruc: '12345678901', billing_address: 'Av. Javier Prado 456', delivery_address: 'Av. Universitaria 654', telephone: '1234567', contact: 'Don Jose')
aguardiente = Client.create(name: 'Aguardiente', ruc: '12345678901', billing_address: 'Av. Javier Prado 456', delivery_address: 'Av. Universitaria 654', telephone: '1234567', contact: 'Don Jose')
propebis = Business.create(name: 'Propebis', ruc: '12345678901', billing_address: 'Av. La marina 123', delivery_address: 'Av. La Molina 987', telephone: '1234567', contact: 'Melba', active: 1)
emca = Business.create(name: 'EMCA', ruc: '12345678901', billing_address: 'Av. La marina 456', delivery_address: 'Av. La Molina 654', telephone: '1234567', contact: 'Melba', active: 1)
coralima = Business.create(name: 'Coralima', ruc: '12345678901', billing_address: 'Av. La marina 789', delivery_address: 'Av. La Molina 321', telephone: '1234567', contact: 'Melba', active: 1)
v1 = Vehicle.create(plate: 'ABC123', trademark: 'Toyota', capacity:'10 cajas')
v2 = Vehicle.create(plate: 'DEF123', trademark: 'Nissan', capacity:'10 cajas')
v3 = Vehicle.create(plate: 'GHI123', trademark: 'Mazda', capacity:'10 cajas')
v4 = Vehicle.create(plate: 'JKL123', trademark: 'Hyundai', capacity:'10 cajas')
v5 = Vehicle.create(plate: 'MNO123', trademark: 'Kia', capacity:'10 cajas')
a = Driver.create(name: "Adrian", license:'ABC123')
b = Driver.create(name: "Belisario", license:'ABC123')
c = Driver.create(name: "Corpancho", license:'ABC123')
d = Driver.create(name: "Daniel", license:'ABC123')
e = Driver.create(name: "Efrain", license:'ABC123')
f = Driver.create(name: "Fausto", license:'ABC123')
User.create(name:'Kaihatsu Labs', email: 'vasquez.alf@gmail.com', username: 'admin', password: 'kaihatsu', password_confirmation: 'kaihatsu', roles_mask: 1)
Setting.create(expiration_alert: 30)
compra = PurchaseOrder.create(supplier: pepe, business: propebis, order_number: '0001', date: Date.strptime('01/12/2016', '%d/%m/%Y'), order_date: Date.strptime('20/11/2016', '%d/%m/%Y'), delivery_date: Date.strptime('10/12/2016', '%d/%m/%Y'), billing_address: 'Av. La marina 123', delivery_address: 'Av. La Molina 987', ammount: 1000)
PurchaseOrderDetail.create(purchase_order: compra, product: leche_gloria, quantity: 100, unit_price: 10, subtotal: 1000)
contrato1 = Contract.create(client: oruga, business: propebis, contract_number: '0001', date: Date.strptime('01/12/2016', '%d/%m/%Y'), start_date: Date.strptime('01/12/2016', '%d/%m/%Y'), end_date: Date.strptime('31/03/2017', '%d/%m/%Y'),final_price: 3000, credit: 0, active: false)
ContractDetail.create(contract: contrato1, product: leche_gloria, quantity: 1500, pending: 1500,unit_price: 1, subtotal: 1500)
ContractDetail.create(contract: contrato1, product: azucar_cartavio, quantity: 1500, pending:0 ,unit_price: 1, subtotal: 1500)
contrato2 = Contract.create(client: hospital, business: emca, contract_number: '0002', date: Date.strptime('01/11/2016', '%d/%m/%Y'), start_date: Date.strptime('01/11/2016', '%d/%m/%Y'), end_date: Date.strptime('28/02/2017', '%d/%m/%Y'),final_price: 4500, credit: 2250, active: true)
ContractDetail.create(contract: contrato2, product: leche_gloria, quantity: 1500, pending: 0, unit_price: 2, subtotal: 1500)
ContractDetail.create(contract: contrato2, product: azucar_cartavio, quantity: 1500, pending: 0, unit_price: 1, subtotal: 1500)
ordenventa1 = SalesOrder.create(business: propebis, client: oruga, contract_id: contrato1.id, sales_order_number: '0001', date: Date.strptime('13/12/2016', '%d/%m/%Y'), billing_address: oruga.billing_address, delivery_address: oruga.delivery_address, order_date: Date.strptime('11/12/2016', '%d/%m/%Y'), delivery_date: Date.strptime('20/12/2016', '%d/%m/%Y'), ammount: 500, status: 2)
SalesOrderDetail.create(sales_order: ordenventa1, product: leche_gloria, quantity: 1500, unit_price: 1, subtotal: 1500)
ordenventa2 = SalesOrder.create(business: propebis, client: oruga, contract_id: contrato1.id, sales_order_number: '0002', date: Date.strptime('14/12/2016', '%d/%m/%Y'), billing_address: oruga.billing_address, delivery_address: oruga.delivery_address, order_date: Date.strptime('12/12/2016', '%d/%m/%Y'), delivery_date: Date.strptime('21/12/2016', '%d/%m/%Y'), ammount: 500, status: 1)
SalesOrderDetail.create(sales_order: ordenventa2, product: azucar_cartavio, quantity: 1500, unit_price: 1, subtotal: 1500)
ordenventa3 = SalesOrder.create(business: emca, client: hospital, contract_id: contrato2.id, sales_order_number: '0003', date: Date.strptime('15/12/2016', '%d/%m/%Y'), billing_address: oruga.billing_address, delivery_address: oruga.delivery_address, order_date: Date.strptime('13/12/2016', '%d/%m/%Y'), delivery_date: Date.strptime('22/12/2016', '%d/%m/%Y'), ammount: 2250, status: 0)
SalesOrderDetail.create(sales_order: ordenventa3, product: leche_gloria, quantity: 750, unit_price: 2, subtotal: 1500)
SalesOrderDetail.create(sales_order: ordenventa3, product: azucar_cartavio, quantity: 750, unit_price: 1, subtotal: 750)
ordenventa4 = SalesOrder.create(business: emca, client: hospital, contract_id: contrato2.id, sales_order_number: '0004', date: Date.strptime('16/12/2016', '%d/%m/%Y'), billing_address: oruga.billing_address, delivery_address: oruga.delivery_address, order_date: Date.strptime('14/12/2016', '%d/%m/%Y'), delivery_date: Date.strptime('23/12/2016', '%d/%m/%Y'), ammount: 2250, status: 3)
SalesOrderDetail.create(sales_order: ordenventa4, product: leche_gloria, quantity: 750, unit_price: 2, subtotal: 1500)
SalesOrderDetail.create(sales_order: ordenventa4, product: azucar_cartavio, quantity: 750, unit_price: 1, subtotal: 750)
ordenventa5 = SalesOrder.create(business: coralima, client: aguardiente, contract_id: 0, sales_order_number: '0005', date: Date.strptime('17/12/2016', '%d/%m/%Y'), billing_address: oruga.billing_address, delivery_address: oruga.delivery_address, order_date: Date.strptime('15/12/2016', '%d/%m/%Y'), delivery_date: Date.strptime('24/12/2016', '%d/%m/%Y'), ammount: 1500, status: 4)
SalesOrderDetail.create(sales_order: ordenventa5, product: azucar_cartavio, quantity: 1500, unit_price: 1, subtotal: 1500)
guiaR1 = RemissionGuide.create(business: propebis, client: oruga, driver: a, vehicle: v1, sales_order: ordenventa1, remission_guide_number: '0001', initial_point: propebis.delivery_address, final_point: oruga.delivery_address, date: Date.strptime('20/12/2016', '%d/%m/%Y'), ammount: 1500)
RemissionGuideDetail.create(remission_guide: guiaR1, product: azucar_cartavio, quantity: 1500, unit_price: 1, subtotal: 1500)
guiaR2 = RemissionGuide.create(business: propebis, client: oruga, driver: b, vehicle: v2, sales_order: ordenventa2, remission_guide_number: '0002', initial_point: propebis.delivery_address, final_point: oruga.delivery_address, date: Date.strptime('21/12/2016', '%d/%m/%Y'), ammount: 1500)
RemissionGuideDetail.create(remission_guide: guiaR2, product: azucar_cartavio, quantity: 1500, unit_price: 1, subtotal: 1500)
guiaR3 = RemissionGuide.create(business: emca, client: hospital, driver: c, vehicle: v3, sales_order: ordenventa3, remission_guide_number: '0003', initial_point: emca.delivery_address, final_point: hospital.delivery_address, date: Date.strptime('22/12/2016', '%d/%m/%Y'), ammount: 2250)
RemissionGuideDetail.create(remission_guide: guiaR3, product: leche_gloria, quantity: 750, unit_price: 2, subtotal: 1500)
RemissionGuideDetail.create(remission_guide: guiaR3, product: azucar_cartavio, quantity: 750, unit_price: 1, subtotal: 750)
guiaI1 = ControlGuide.create(business: emca, client: hospital, driver: d, vehicle: v4, sales_order: ordenventa4, control_guide_number: '0001', initial_point: emca.delivery_address, final_point: hospital.delivery_address, date: Date.strptime('23/12/2016', '%d/%m/%Y'), ammount: 2250)
ControlGuideDetail.create(control_guide: guiaI1, product: leche_gloria, quantity: 750, unit_price: 2, subtotal: 1500)
ControlGuideDetail.create(control_guide: guiaI1, product: azucar_cartavio, quantity: 750, unit_price: 1, subtotal: 750)
guiaI2 = ControlGuide.create(business: propebis, client: oruga, driver: e, vehicle: v5, sales_order: ordenventa2, control_guide_number: '0001', initial_point: propebis.delivery_address, final_point: oruga.delivery_address, date: Date.strptime('24/12/2016', '%d/%m/%Y'), ammount: 1500)
ControlGuideDetail.create(control_guide: guiaI2, product: azucar_cartavio, quantity: 1500, unit_price: 1, subtotal: 1500)
guiaI3 = ControlGuide.create(business: emca, client: hospital, driver: f, vehicle: v1, sales_order: ordenventa3, control_guide_number: '0002', initial_point: emca.delivery_address, final_point: hospital.delivery_address, date: Date.strptime('25/12/2016', '%d/%m/%Y'), ammount: 2250)
ControlGuideDetail.create(control_guide: guiaI3, product: leche_gloria, quantity: 750, unit_price: 2, subtotal: 1500)
ControlGuideDetail.create(control_guide: guiaI3, product: azucar_cartavio, quantity: 750, unit_price: 1, subtotal: 750)
factura1 = Invoice.create(business: emca, client: hospital, sales_order: ordenventa3, invoice_number: '0001', date: Date.strptime('26/12/2016', '%d/%m/%Y'), ammount: 2250)
InvoiceDetail.create(invoice: factura1, product: leche_gloria, quantity: 750, unit_price: 2, subtotal: 1500)
InvoiceDetail.create(invoice: factura1, product: azucar_cartavio, quantity: 750, unit_price: 1, subtotal: 750)